### PR TITLE
Created scripts to make things easier

### LINKED ISSUE #37: 'dino' is missing
There's `dinos` and `dinosaur` but no `dino`

### PR DESCRIPTION
**Pull request by InnovativeInventor**
I created some scripts to make things easier. Just run `bash scripts/create.sh` and the words added to `words.txt` will be sorted, `words_alpha.txt` will be updated, `words_dictionary.json` is updated, and all the .zip files are updated. This makes life a lot easier, I think. I also added dino to the words to fix #37.

### CODE REVIEW

**Comment by NonlinearFruit** [comment]
These scripts are sorely needed

**Comment by nelsonic** [comment]
@NonlinearFruit we agree. The scripts look good. 👍 
Sadly there are merge conflicts which prevent merging the pull request.
@InnovativeInventor if you have time to fix the merge conflicts we can merge the PR. 
Thanks.

**Comment by InnovativeInventor** [comment]
Ok, I've updated the word lists to include the most recent set of words (as of commit 54b470a763d3df98ec33cb049382711972975317)

Here is exactly what I did:
```
aria2c https://github.com/dwyl/english-words/raw/master/words.txt
cat words.1.txt >> words.txt
rm words.1.txt
bash scripts/create.sh
```
Everything worked and resulted in 0 errors (although I got a warning with the find command). Hopefully this is acceptable for you.

**Comment by nelsonic** [comment]
@InnovativeInventor its strange that GitHub is still reporting merge conflicts... 😞

**Comment by InnovativeInventor** [comment]
Ok, I'll just create a new pull request with just the script (you can run it yourself and push to master).

I think this is due to the original words.txt not being properly sorted (I think there is an issue/PR about that).

**Comment by nelsonic** [comment]
@InnovativeInventor yeah, sounds good. If you have time, create a PR with just the useful scrips and we will merge. Thanks!

**Comment by InnovativeInventor** [comment]
Ok, I force-pushed the repo to just have my scripts (whoops, I think I should have either created a different branch or added another commit). 

Anyways, this should be mergeable now. @nelsonic

**Pull request merged**
